### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mark-unwin** [svenbolte/Open-Audit-Classic#1]
Open-AudIT was never GPL licensed. It has always been AGPL licensed. Could you please change the license on this project to AGPL.

Your readme states "Since the main developer left". I am the main developer. I have always been the developer. I have never left. Please change your readme to show this (or remove the above).

Thanks.
Mark Unwin.

**Comment by mark-unwin** [comment]
Open-AudIT war nie GPL-lizenziert. Es war schon immer AGPL-lizenziert. Könnten Sie bitte die Lizenz für dieses Projekt auf AGPL ändern?

In Ihrer Readme-Datei steht „Seitdem der Hauptentwickler gegangen ist“. Ich bin der Hauptentwickler. Ich war schon immer der Entwickler. Ich bin nie gegangen. Bitte ändern Sie Ihre Readme-Datei, um dies anzuzeigen (oder entfernen Sie das Obige).

**Comment by svenbolte** [comment]
Hi Mark,

i partially disagree. When i forked the source code, files with time stamp:  2010-08-31 had a GPLv3 license. there was a gpl.txt in the openaudit source dir and even the gplv3 logo was displayed on info display.

I changed the sentences in readme.md about you and added a notice that your Open-Audit project is AGPL licensed. 

I keep my fork "OpenAudit Classic" on gplv3 status.

**Comment by svenbolte** [comment]
Update: Looking closer to it i think the Affero GPL license is the better for use, i switched and changed the gpl text content and the Fork to AGPL as you advised.

**Comment by mark-unwin** [comment]
Thanks - very much appreciated :-)
